
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 07 23:02:04 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 44;
  public static final int LBRACKET = 15;
  public static final int CONST = 11;
  public static final int MINUS_MINUS = 20;
  public static final int NOT_EQUAL = 37;
  public static final int LPAREN = 17;
  public static final int GREATER = 31;
  public static final int SEMI = 13;
  public static final int CONTINUE = 3;
  public static final int NUM_CONST = 43;
  public static final int FOR = 42;
  public static final int LESS = 36;
  public static final int MINUS = 21;
  public static final int RPAREN = 18;
  public static final int AND = 35;
  public static final int OR = 2;
  public static final int COMMA = 12;
  public static final int CLASS = 28;
  public static final int DIV = 24;
  public static final int LESS_EQUAL = 29;
  public static final int PLUS = 22;
  public static final int IF = 39;
  public static final int THIS = 32;
  public static final int DOT = 38;
  public static final int ABSTRACT = 4;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int PLUS_PLUS = 19;
  public static final int RBRACKET = 16;
  public static final int EQUAL = 14;
  public static final int GREATER_EQUAL = 30;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int MOD = 25;
  public static final int IDENT = 46;
  public static final int BREAK = 33;
  public static final int VOID = 7;
  public static final int TIMES = 23;
  public static final int ELSE = 40;
  public static final int LBRACE = 9;
  public static final int READ = 5;
  public static final int RBRACE = 10;
  public static final int EXTENDS = 41;
  public static final int PROG = 8;
  public static final int BOOL_CONST = 45;
  public static final int EQUAL_EQUAL = 34;
  public static final int PRINT = 6;
}

